//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comi_muni_membresia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comi_muni_membresia()
        {
            this.pago = new HashSet<pago>();
        }

        [Key]
        public int id_comi_muni_membresia { get; set; }
        public int id_membresia { get; set; }
        public int id_comi_muni { get; set; }
        public int cant_meses { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public System.DateTime fec_modificacion { get; set; }
        public string usuario_mod { get; set; }
        public bool estado { get; set; }
    
        public virtual comi_muni comi_muni { get; set; }
        public virtual membresia membresia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pago { get; set; }
    }
}
