//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conectaDBEntities : DbContext
    {
        public conectaDBEntities()
            : base("name=conectaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comi_muni> comi_muni { get; set; }
        public virtual DbSet<comi_muni_membresia> comi_muni_membresia { get; set; }
        public virtual DbSet<configuracion> configuracion { get; set; }
        public virtual DbSet<denuncia> denuncia { get; set; }
        public virtual DbSet<estado_denuncia> estado_denuncia { get; set; }
        public virtual DbSet<jurisdiccion> jurisdiccion { get; set; }
        public virtual DbSet<membresia> membresia { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<patrullero> patrullero { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<punto_sector> punto_sector { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rol_permiso> rol_permiso { get; set; }
        public virtual DbSet<seccion> seccion { get; set; }
        public virtual DbSet<sub_seccion> sub_seccion { get; set; }
        public virtual DbSet<tipo_denuncia> tipo_denuncia { get; set; }
        public virtual DbSet<tipo_muni> tipo_muni { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_muni> usuario_muni { get; set; }
    }
}
