//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class membresia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membresia()
        {
            this.comi_muni_membresia = new HashSet<comi_muni_membresia>();
        }
    
        public int id_membresia { get; set; }
        public string descripcion { get; set; }
        public int cant_usuarios { get; set; }
        public int dias_duracion { get; set; }
        public decimal costo { get; set; }
        public int limite_reportes_dia { get; set; }
        public int limite_usuarios { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public System.DateTime fec_modificacion { get; set; }
        public string usuario_mod { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comi_muni_membresia> comi_muni_membresia { get; set; }
    }
}
