//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id_pago { get; set; }
        public int id_comi_muni_membresia { get; set; }
        public decimal monto { get; set; }
        public byte[] cod_transaccion { get; set; }
        public System.DateTime fec_modificacion { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public string usuario_mod { get; set; }
    
        public virtual comi_muni_membresia comi_muni_membresia { get; set; }
    }
}
