//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class punto_sector
    {
        public int id_punto_jurisdiccion { get; set; }
        public int id_jurisdiccion { get; set; }
        public decimal longitud { get; set; }
        public decimal latitud { get; set; }
        public int orden { get; set; }
    
        public virtual jurisdiccion jurisdiccion { get; set; }
    }
}
