//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class rol_permiso
    {
        [Key]
        public int id_rol_permiso { get; set; }
        public int id_rol { get; set; }
        public int id_permiso { get; set; }
    
        public virtual permiso permiso { get; set; }
        public virtual rol rol { get; set; }
    }
}
