//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sub_seccion
    {
        [Key]
        public int id_sub_seccion { get; set; }
        public string descripcion { get; set; }
        public int id_seccion { get; set; }
    
        public virtual seccion seccion { get; set; }
    }
}
