//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSql
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.denuncia = new HashSet<denuncia>();
            this.usuario_muni = new HashSet<usuario_muni>();
        }
    
        [Key]
        public int id_usuario { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string foto_perfil { get; set; }
        public int tipo_usuario { get; set; }
        public int id_jurisdiccion { get; set; }
        public int id_persona { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public System.DateTime fec_modificacion { get; set; }
        public string usuario_mod { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<denuncia> denuncia { get; set; }
        public virtual persona persona { get; set; }
        public virtual tipo_usuario tipo_usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_muni> usuario_muni { get; set; }
    }
}
